### PR TITLE
Added searchParams to URL object

### PR DESCRIPTION
**Pull request by sapsiero**
I wanted to add searchParams to the URL class. Hope this is helpful.

### CODE REVIEW

**Comment by abdonrd** [comment]
@azakus any option to merge it? I'm also interested in `searchParams`.

**Comment by abdonrd** [comment]
@azakus @TimvdLippe any option to merge it? I'm also interested in `searchParams`.

**Comment by TimvdLippe** [comment]
We will need to clean up this code a bit to make it more readable and add the appropriate tests to verify it is working.

**Comment by abdonrd** [comment]
@TimvdLippe thanks! I hope it will be soon! 😃

**Comment by azakus** [comment]
Ported to the monorepo as webcomponents/polyfills#7

**Pull request closed without merging**
